name: flutter_clipboard_mgr
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.3.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    window_manager: ^0.3.8
    cupertino_icons:
    super_clipboard:
    clipboard_watcher: ^0.2.0
    link_preview_generator: ^1.2.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    hive_generator: ^2.0.1
    build_runner: ^2.4.9

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - lib/assets/
